# Домашнее задание 2 (5 баллов).

Все задания ниже имеют равный вес (5/16).

In [63]:
import pandas as pd

#### Описание данных

В папке Dat (https://github.com/hse-ds/iad-intro-ds/blob/master/2023/homeworks/Data.zip) находится информация о студентах. Всего 10 групп студентов. Файлы делятся на две категории:
    * Students_info_i - информация о студентах из группы i
    * Students_marks_i - оценки студентов из группы i за экзамены

### Одно из важных достоинств pandas $-$ это удобные методы реляционного взаимодействия с данными, аналогичные, например, возможностям SQL для слияния и конкатенации таблиц: merge, join, concat. Наличие готовых методов позволяет не реализовывать самостоятельно поэлементную обработку данных и оперировать сразу целыми таблицами данных.

Подробно об этих методах посмотрите тут: https://www.kaggle.com/residentmario/renaming-and-combining#Combining

#### Задание 1. Соберите всю информацию о студентах в одну таблицу df. В получившейся таблице должна быть информация и оценки всех студентов из всех групп. Напечатайте несколько строк таблицы для демонстрации результата.¶

In [64]:
data0 = pd.read_csv('Students_info_0.csv', delimiter=',')
data1 = pd.read_csv('Students_info_1.csv', delimiter=',')
data2 = pd.read_csv('Students_info_2.csv', delimiter=',')
data3 = pd.read_csv('Students_info_3.csv', delimiter=',')
data4 = pd.read_csv('Students_info_4.csv', delimiter=',')
data5 = pd.read_csv('Students_info_5.csv', delimiter=',')
data6 = pd.read_csv('Students_info_6.csv', delimiter=',')
data7 = pd.read_csv('Students_info_7.csv', delimiter=',')
data8 = pd.read_csv('Students_info_8.csv', delimiter=',')
data9 = pd.read_csv('Students_info_9.csv', delimiter=',')

marks0 = pd.read_csv('Students_marks_0.csv', delimiter=',')
marks1 = pd.read_csv('Students_marks_1.csv', delimiter=',')
marks2 = pd.read_csv('Students_marks_2.csv', delimiter=',')
marks3 = pd.read_csv('Students_marks_3.csv', delimiter=',')
marks4 = pd.read_csv('Students_marks_4.csv', delimiter=',')
marks5 = pd.read_csv('Students_marks_5.csv', delimiter=',')
marks6 = pd.read_csv('Students_marks_6.csv', delimiter=',')
marks7 = pd.read_csv('Students_marks_7.csv', delimiter=',')
marks8 = pd.read_csv('Students_marks_8.csv', delimiter=',')
marks9 = pd.read_csv('Students_marks_9.csv', delimiter=',')

df = pd.merge(pd.concat([data0, data1, data2, data3, data4, data5, data6, data7, data8, data9]),pd.concat([marks0, marks1, marks2, marks3, marks4, marks5, marks6, marks7, marks8, marks9]))
df

,index,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score
0,0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,1,female,group C,some college,standard,completed,group1,69,90,88
2,2,female,group B,master's degree,standard,none,group1,90,95,93
3,3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,4,male,group C,some college,standard,none,group1,76,78,75
...,...,...,...,...,...,...,...,...,...,...
995,995,female,group E,master's degree,standard,completed,group10,88,99,95
996,996,male,group C,high school,free/reduced,none,group10,62,55,55
997,997,female,group C,high school,free/reduced,completed,group10,59,71,65
998,998,female,group D,some college,standard,completed,group10,68,78,77
999,999,female,group D,some college,free/reduced,none,group10,77,86,86

#### Задание 2. Удалите столбец index у полученной таблицы. Напечатайте первые 10 строк таблицы.

In [42]:
df.pop("index")
df.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,female,group C,some college,standard,completed,group1,69,90,88
2,female,group B,master's degree,standard,none,group1,90,95,93
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,male,group C,some college,standard,none,group1,76,78,75
5,female,group B,associate's degree,standard,none,group1,71,83,78
6,female,group B,some college,standard,completed,group1,88,95,92
7,male,group B,some college,free/reduced,none,group1,40,43,39
8,male,group D,high school,free/reduced,completed,group1,64,64,67
9,female,group B,high school,free/reduced,none,group1,38,60,50

#### Задание 3. Выведите на экран размеры полученной таблицы

In [43]:
df.shape

(1000, 9)

#### Задание 4. Выведите на экран статистические характеристики числовых столбцов таблицы (минимум, максимум, среднее значение, стандартное отклонение)

In [46]:
df.describe().loc[['mean', 'std', 'min', 'max']]

      math score  reading score  writing score
mean    66.08900      69.169000      68.054000
std     15.16308      14.600192      15.195657
min      0.00000      17.000000      10.000000
max    100.00000     100.000000     100.000000

#### Задание 5. Проверьте, есть ли в таблице пропущенные значения

In [8]:
df.isnull().any().any()

False

#### Задание 6. Выведите на экран средние баллы студентов по каждому предмету (math, reading, writing)

In [47]:
print(df.mean())

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

<ipython-input-47-f98cceecb4a0>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(df.mean())

**Задание 7. Как зависят оценки от того, проходил ли студент курс для подготовки к сдаче экзамена (test preparation course)? Выведите на экран для каждого предмета в отдельности средний балл студентов, проходивших курс для подготовки к экзамену и не проходивших курс.**

In [10]:
succes_course = df[(df["test preparation course"] == "completed")]
pitty_course = df[(df["test preparation course"] == "none")]
print(succes_course.mean())
print(pitty_course.mean())

math score       69.695531
reading score    73.893855
writing score    74.418994
dtype: float64
math score       64.077882
reading score    66.534268
writing score    64.504673
dtype: float64

<ipython-input-10-d0595d3aa382>:3: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(succes_course.mean())
<ipython-input-10-d0595d3aa382>:4: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(pitty_course.mean())

**Задание 8. Выведите на экран все различные значения из столбца lunch.**

In [11]:
df['lunch'].unique()

array(['standard', 'free/reduced'], dtype=object)

**Задание 9. Переименуйте колонку "parental level of education" в "education", а "test preparation course" в "test preparation" с помощью метода pandas rename**
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html

In [55]:
df.rename(columns = {"parental level of education" : "education", "test preparation course" : "test preparation"}, inplace = True )

**Зафиксируем минимальный балл для сдачи экзамена**

In [13]:
passmark = 50

**Задание 10. Ответьте на вопросы:**
    * Какая доля студентов сдала экзамен по математике (passmark >= 50)?
    * Какая доля студентов, проходивших курс подготовки к экзамену, сдала экзамен по математике?
    * Какая доля женщин, не проходивших курс подготовки к экзамену, не сдала экзамен по математике?

In [60]:
print(len(df[(df["math score"] >= 50)]) / len(df))

students_passed_math_exam = len(df[(df["test preparation"] == "completed") & (df["math score"] >= passmark)])
students_had_a_course = len(df[df["test preparation"] == "completed"])
print(prep_pass_math_count / prep_students_count)

women_donnot_pass = len(df[(df["test preparation"] == "none") & (df["gender"] == "female") & (df["math score"] < passmark)])
women_didnot_have_a_course = len(df[(df["test preparation"] == "none") & (df["gender"] == "female")])
print(women_donnot_pass/women_didnot_have_a_course)

0.865
0.9217877094972067
0.20958083832335328

**Задание 11. С помощью groupby выполните задания ниже. Также выведите время выполнения каждого из заданий.**
    * Для каждой этнической группы выведите средний балл за экзамен по чтению
    * Для каждого уровня образования выведите минимальный балл за экзамен по письму

In [15]:
%%time
print(df.groupby(['race/ethnicity'])['reading score'].mean())

race/ethnicity
group A    64.674157
group B    67.352632
group C    69.103448
group D    70.030534
group E    73.028571
Name: reading score, dtype: float64
CPU times: user 5.05 ms, sys: 0 ns, total: 5.05 ms
Wall time: 9.35 ms

In [30]:
%%time
print(df.groupby(['education'])['writing score'].min())

education
associate's degree    35
bachelor's degree     38
high school           15
master's degree       46
some college          19
some high school      10
Name: writing score, dtype: int64
CPU times: user 4.25 ms, sys: 0 ns, total: 4.25 ms
Wall time: 5.12 ms

**Задание 12. Выполните задание 11 с помощью циклов. Сравните время выполнения.**

In [16]:
%%time
for ethnicit, a in df.groupby('race/ethnicity'):
    mean_reading_score = a['reading score'].mean()
    print( mean_reading_score)

64.67415730337079
67.35263157894737
69.10344827586206
70.03053435114504
73.02857142857142
CPU times: user 5.29 ms, sys: 918 µs, total: 6.21 ms
Wall time: 7.71 ms

In [18]:
%%time
for level, b in df.groupby('education'):
    min_writing_score = b['writing score'].min()
    print( min_writing_score)

35
38
15
46
19
10
CPU times: user 5.41 ms, sys: 745 µs, total: 6.16 ms
Wall time: 7.85 ms

**Задание 13. Выведите на экран средние баллы студентов по каждому предмету в зависимости от пола и уровня образования. То есть должно получиться количество групп, равных 2 * (число уровней образования), и для каждой такой группы выыведите средний балл по каждому из предметов.**

Это можно сделать с помощью сводных таблиц (pivot_table):

https://www.kaggle.com/kamilpolak/tutorial-how-to-use-pivot-table-in-pandas

In [39]:
grouped = pd.pivot_table(df,index=['gender','education'])
grouped

<ipython-input-39-29e28edb2550>:1: FutureWarning: pivot_table dropped a column because it failed to aggregate. This behavior is deprecated and will raise in a future version of pandas. Select only the columns that can be aggregated.
  grouped = pd.pivot_table(df,index=['gender','education'])

                           math score  reading score  writing score
gender education
female associate's degree   65.250000      74.120690      74.000000
       bachelor's degree    68.349206      77.285714      78.380952
       high school          59.351064      68.202128      66.691489
       master's degree      66.500000      76.805556      77.638889
       some college         65.406780      73.550847      74.050847
       some high school     59.296703      69.109890      68.285714
male   associate's degree   70.764151      67.433962      65.405660
       bachelor's degree    70.581818      68.090909      67.654545
       high school          64.705882      61.480392      58.539216
       master's degree      74.826087      73.130435      72.608696
       some college         69.009259      64.990741      63.148148
       some high school     67.840909      64.693182      61.375000

#### Задание 14. Сколько студентов успешно сдали экзамен по математике?

Создайте новый столбец в таблице df под названием Math_PassStatus и запишите в него F, если студент не сдал экзамен по математике (балл за экзамен < passmark), и P иначе.

Посчитайте количество студентов, сдавших и не сдавших экзамен по математике.

Сделайте аналогичные шаги для экзаменов по чтению и письму.

In [21]:
df['Math_PassStatus'] = df['math score'].apply(lambda x: 'P' if x >= 50 else 'F')
print("Кол-во человек несдавших экзамен по математике:", len(df[df['Math_PassStatus']=='F']))
print("Кол-во человек сдавших экзамен по математике:",len(df[df['Math_PassStatus']=='P']))
df['Writing_PassStatus'] = df['writing score'].apply(lambda x: 'P' if x >= 50 else 'F')
print("Кол-во человек несдавших экзамен по письму:",len(df[df['Writing_PassStatus']=='F']))
print("Кол-во человек сдавших экзамен по письму:",len(df[df['Writing_PassStatus']=='P']))
df['Reading_PassStatus'] = df['reading score'].apply(lambda x: 'P' if x >= 50 else 'F')
print("Кол-во человек несдавших экзамен по чтению:",len(df[df['Reading_PassStatus']=='F']))
print("Кол-во человек сдавших экзамен по чтению:",len(df[df['Reading_PassStatus']=='P']))
df

Кол-во человек несдавших экзамен по математике: 135
Кол-во человек сдавших экзамен по математике: 865
Кол-во человек несдавших экзамен по письму: 114
Кол-во человек сдавших экзамен по письму: 886
Кол-во человек несдавших экзамен по чтению: 90
Кол-во человек сдавших экзамен по чтению: 910

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,Grade,OverAll_PassStatus,Math_PassStatus,Writing_PassStatus,Reading_PassStatus
0,female,group B,bachelor's degree,standard,none,group1,72,72,74,C,P,P,P,P
1,female,group C,some college,standard,completed,group1,69,90,88,B,P,P,P,P
2,female,group B,master's degree,standard,none,group1,90,95,93,A,P,P,P,P
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,F,F,F,F,P
4,male,group C,some college,standard,none,group1,76,78,75,C,P,P,P,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,group10,88,99,95,A,P,P,P,P
996,male,group C,high school,free/reduced,none,group10,62,55,55,E,P,P,P,P
997,female,group C,high school,free/reduced,completed,group10,59,71,65,D,P,P,P,P
998,female,group D,some college,standard,completed,group10,68,78,77,C,P,P,P,P
999,female,group D,some college,free/reduced,none,group10,77,86,86,B,P,P,P,P

#### Задание 15. Сколько студентов успешно сдали все экзамены?

Создайте столбец OverAll_PassStatus и запишите в него для каждого студента 'F', если студент не сдал хотя бы один из трех экзаменов, а иначе 'P'.

Посчитайте количество студентов, которые сдали все экзамены.

In [61]:
df['OverAll_PassStatus'] = 'P'
df.loc[(df['math score'] < passmark) | (df['reading score'] < passmark) | (df['writing score'] < passmark), 'OverAll_PassStatus'] = 'F'
print("Кол-во человек, сдавших все экзамены:", len(df[df['OverAll_PassStatus']=='P']))
df

Кол-во человек, сдавших все экзамены: 812

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,OverAll_PassStatus
0,female,group B,bachelor's degree,standard,none,group1,72,72,74,P
1,female,group C,some college,standard,completed,group1,69,90,88,P
2,female,group B,master's degree,standard,none,group1,90,95,93,P
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,F
4,male,group C,some college,standard,none,group1,76,78,75,P
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,group10,88,99,95,P
996,male,group C,high school,free/reduced,none,group10,62,55,55,P
997,female,group C,high school,free/reduced,completed,group10,59,71,65,P
998,female,group D,some college,standard,completed,group10,68,78,77,P
999,female,group D,some college,free/reduced,none,group10,77,86,86,P

#### Задание 16. Переведем баллы в оценки

### Система перевода баллов в оценки
####    больше 90 = A
####      80-90 = B
####      70-80 = C
####      60-70 = D
####      50-60 = E
####    меньше 50 = F (Fail)

Создайте вспомогательную функцию, которая будет по среднему баллу за три экзамена выставлять оценку студенту по данным выше критериям.

Создайте столбец Grade и запишите в него оценку каждого студента.

Выведите количество студентов, получивших каждую из оценок.

**В случае, если средний балл попадает на границу между оценками (т.е. равен ровно 60, 70 или 80 баллов), вы можете интерпретировать условие на своё усмотрение (т.е. можете поставить за 60 баллов оценку D, а можете - E).**

In [62]:
def GetGrade(final_avg_mark):
    if final_avg_mark > 90:
        return 'A'
    elif 80 <= final_avg_mark <= 90:
        return 'B'
    elif 70 <= final_avg_mark < 80:
        return 'C'
    elif 60 <= final_avg_mark < 70:
        return 'D'
    elif 50 <= final_avg_mark < 60:
        return 'E'
    else:
        return 'F'
final_avg_mark = (df["math score"] + df["reading score"] + df["writing score"])/3
df['Grade'] = final_avg_mark.apply(GetGrade)
print("Кол-во учеников получивших A:",len(df[(df["Grade"] == "A")]))
print("Кол-во учеников получивших B:",len(df[(df["Grade"] == "B")]))
print("Кол-во учеников получивших C:",len(df[(df["Grade"] == "C")]))
print("Кол-во учеников получивших D:",len(df[(df["Grade"] == "D")]))
print("Кол-во учеников получивших E:",len(df[(df["Grade"] == "E")]))
print("Кол-во учеников получивших F:",len(df[(df["Grade"] == "F")]))
df

Кол-во учеников получивших A: 50
Кол-во учеников получивших B: 148
Кол-во учеников получивших C: 261
Кол-во учеников получивших D: 256
Кол-во учеников получивших E: 182
Кол-во учеников получивших F: 103

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,OverAll_PassStatus,Grade
0,female,group B,bachelor's degree,standard,none,group1,72,72,74,P,C
1,female,group C,some college,standard,completed,group1,69,90,88,P,B
2,female,group B,master's degree,standard,none,group1,90,95,93,P,A
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,F,F
4,male,group C,some college,standard,none,group1,76,78,75,P,C
...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,group10,88,99,95,P,A
996,male,group C,high school,free/reduced,none,group10,62,55,55,P,E
997,female,group C,high school,free/reduced,completed,group10,59,71,65,P,D
998,female,group D,some college,standard,completed,group10,68,78,77,P,C
999,female,group D,some college,free/reduced,none,group10,77,86,86,P,B